Repository vRaj-Ajmera/NemoKartAnalysis, pull requests merged in 2024-12, with the labels that each got.

#12 Raj kart matrix
  docs/assets/css/style.css
  docs/assets/js/kart_stats.js
  docs/assets/kart_graphs/Shanghai by Night_kart_placements.png
  docs/assets/kart_graphs/Shanghai by Night_win_rate_heatmap.png
  docs/assets/kart_graphs/Shanghai_kart_placements.png
  docs/assets/kart_graphs/Shanghai_win_rate_heatmap.png
  docs/assets/kart_graphs/Snowville_kart_placements.png
  docs/assets/kart_graphs/Snowville_win_rate_heatmap.png
  docs/index.html
  docs/kart_stats.html
  output/kart_graphs/Shanghai by Night_kart_placements.png
  output/kart_graphs/Shanghai by Night_win_rate_heatmap.png
  output/kart_graphs/Shanghai_kart_placements.png
  output/kart_graphs/Shanghai_win_rate_heatmap.png
  output/kart_graphs/Snowville_kart_placements.png
  output/kart_graphs/Snowville_win_rate_heatmap.png
  output/kart_post_analysis.json
  src/calculations/kart_analysis.py
Labels: enhancement, stats

#15 Azhan profilepics PR
  docs/assets/css/style.css
  docs/assets/icons/Azhan.png
  docs/assets/icons/Raj.png
  docs/assets/icons/Sameer.png
  docs/assets/icons/Zetaa.png
  docs/assets/icons/default.png
  docs/assets/js/main.js
  docs/assets/js/player_stats.js
Labels: enhancement

#16 Completed profile pic addition
  docs/assets/css/style.css
  docs/assets/icons/Azhan.png
  docs/assets/icons/Raj.png
  docs/assets/icons/Sameer.png
  docs/assets/icons/Zetaa.png
  docs/assets/icons/default.png
  docs/assets/js/main.js
  docs/assets/js/player_stats.js
Labels: enhancement

#25 EasyOCR Integration for Image-to-Text Logging
  data/Race_Screenshots/license_plate.jpg
  data/Race_Screenshots/race_1_small.png
  data/Race_Screenshots/race_2.png
  data/Race_Screenshots/race_3.png
  data/Race_Screenshots/race_3_small.png
  data/Race_Screenshots/race_4.png
  data/Race_Screenshots/race_5.png
  data/player_aliases.json
  output/img_processing/clipboard_image.png
  output/img_processing/preprocessed_image.png
  src/gui_OCR_logger.py
Labels: enhancement, logging races
